version: '3'
services:
  raspberrypicompiler:
    image: 139.9.186.120:8080/raspberrypi_pico_compiler:latest
    container_name: raspberrypi_pico_compiler
    restart: unless-stopped
    command: /bin/bash
    stdin_open: true
    tty: true
    #devices:
    #  - /dev/ttyUSB0:/dev/ttyUSB0
    volumes:
      - ./workdir:/root/workdir
